version: '3.9'

services:
  mysql:
   image: mysql:8
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: bluenucleus
     MYSQL_USER: user 
     MYSQL_PASSWORD: password
   ports:
     - "3306:3306"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend